const maps = "https://www.google.com/maps/search/?api=1&query=Majestoso%2C+Largo+do+Paissandu+17%2C+Sao+Paulo&query_place_id=ChIJYxuIBlFYzpQRNPFaqNn8o1Q";

const categories = [["01","Lanches","◒"],["02","Beirutes","◇"],["03","Café","◡"],["04","Drinks","▽"],["05","Sucos","▯"],["06","Vitaminas","◫"],["07","Salgados","△"]];

export default function Home() {
  const schema = {"@context":"https://schema.org","@type":"Restaurant",name:"Majestoso",description:"Demonstração conceitual não oficial do Majestoso.",address:{"@type":"PostalAddress",streetAddress:"Largo do Paissandú, 17 - República",addressLocality:"São Paulo",addressRegion:"SP",postalCode:"01034-010",addressCountry:"BR"}};
  return <>
    <header className="nav" aria-label="Navegação principal"><a className="brand" href="#inicio" aria-label="Majestoso — início"><span>M</span><b>MAJESTOSO</b></a><nav><a href="#sobre">O Majestoso</a><a href="#cardapio">Cardápio</a><a href="#ambiente">Ambiente</a><a href="#localizacao">Localização</a></nav><a className="navCta" href="#cardapio">Ver cardápio <span>↘</span></a></header>
    <main id="inicio">
      <section className="hero shell"><div className="heroCopy"><p className="eyebrow">A LANCHONETE MAJESTOSO · CENTRO</p><h1>Sabor no<br/>coração de<br/><em>São Paulo.</em></h1><p className="lead">Lanches, café, bebidas e a energia de uma pausa no coração da cidade.</p><div className="actions"><a className="button primary" href="#cardapio">Ver cardápio <span>↘</span></a><a className="button outline" href={maps} target="_blank" rel="noreferrer">Como chegar <span>⌖</span></a></div><div className="heroMeta"><span>REPÚBLICA</span><span>01034-010</span></div></div><figure className="heroVisual"><img src="/images/majestoso-neon.jpg" alt="Identidade neon do Majestoso com o personagem coroado" fetchPriority="high"/><figcaption><span>Identidade Majestoso</span><b>NEON · VERMELHO · OURO</b></figcaption></figure></section>
      <section className="highlights shell" aria-label="Destaques do Majestoso"><article><span>01</span><div><b>Lanches</b><small>Para uma pausa completa</small></div></article><article><span>02</span><div><b>Café</b><small>Um clássico do dia a dia</small></div></article><article><span>03</span><div><b>Drinks</b><small>Opções para diferentes momentos</small></div></article><article><span>04</span><div><b>No coração de São Paulo</b><small>Largo do Paissandú</small></div></article></section>
      <section className="story shell" id="sobre"><div className="sectionIntro"><p className="eyebrow">01 · O MAJESTOSO</p><h2>Muito mais que<br/>uma <em>lanchonete.</em></h2></div><div className="storyGrid"><figure className="storyPhoto"><img src="/images/majestoso-sala.jpg" alt="Salão do Majestoso com mesas, balcão e iluminação" loading="lazy"/><figcaption>O salão e o balcão em uma só cena.</figcaption></figure><div className="storyCopy"><p>No ritmo do Centro, o Majestoso reúne balcão, mesas, café, lanches e bebidas em um ambiente vivo e autenticamente paulistano.</p><p>A proposta visual nasce do que já existe no espaço: madeira, luz quente, cores fortes e a presença marcante do neon.</p><ul><li><span>✦</span> Uma pausa no Centro de São Paulo</li><li><span>✦</span> Ambiente direto e acolhedor</li><li><span>✦</span> Identidade que não passa despercebida</li></ul></div></div></section>
      <section className="menu" id="cardapio"><div className="shell"><div className="menuHead"><div><p className="eyebrow">02 · CARDÁPIO</p><h2>Escolha o seu<br/><em>favorito.</em></h2></div><p>Uma estrutura visual pronta para receber os itens e preços oficiais. Nesta demonstração, nenhuma informação comercial foi inventada.</p></div><div className="categoryGrid">{categories.map(([n,name,icon])=><article key={name}><span className="catNum">{n}</span><b className="catIcon" aria-hidden="true">{icon}</b><h3>{name}</h3><span className="catArrow">↗</span></article>)}</div></div></section>
      <section className="ambience shell" id="ambiente"><div className="ambienceCopy"><p className="eyebrow">03 · O AMBIENTE</p><h2>Uma pausa com<br/><em>personalidade.</em></h2><p>Entre frutas frescas, bebidas, café e salgados, o balcão traduz o movimento cotidiano do Majestoso.</p><div className="detail"><span>LUZ QUENTE</span><span>MADEIRA</span><span>NEON</span></div></div><figure className="ambiencePhoto"><img src="/images/majestoso-balcao.jpg" alt="Balcão do Majestoso com bebidas, frutas e salgados" loading="lazy"/><figcaption><b>O balcão</b><span>Detalhes reais do espaço</span></figcaption></figure></section>
      <section className="location" id="localizacao"><div className="locationCard"><p className="eyebrow">04 · LOCALIZAÇÃO</p><h2>No centro<br/>de tudo.</h2><address>Largo do Paissandú, 17<br/>República, São Paulo – SP<br/>01034-010, Brasil</address><a className="button mapButton" href={maps} target="_blank" rel="noreferrer">Como chegar <span>⌖</span></a></div><a className="mapVisual" href={maps} target="_blank" rel="noreferrer" aria-label="Abrir localização do Majestoso no Google Maps"><span className="mapPin">●</span><div><b>MAJESTOSO</b><small>Largo do Paissandú · Centro</small></div><em>ABRIR NO GOOGLE MAPS ↗</em></a></section>
    </main>
    <footer><div className="footerTop shell"><a className="brand footerBrand" href="#inicio"><span>M</span><b>MAJESTOSO</b></a><div><p className="footerLabel">NAVEGAÇÃO</p><a href="#sobre">O Majestoso</a><a href="#cardapio">Cardápio</a><a href="#ambiente">Ambiente</a></div><address><p className="footerLabel">ENDEREÇO</p><a href={maps} target="_blank" rel="noreferrer">Largo do Paissandú, 17<br/>República, São Paulo – SP<br/>01034-010, Brasil ↗</a></address></div><div className="disclaimer shell"><b>DEMONSTRAÇÃO CONCEITUAL NÃO OFICIAL</b><p>Este site não é o site oficial do Majestoso. É uma demonstração conceitual criada exclusivamente para apresentação e avaliação. Desenvolvido por Ameer Mustafa.</p></div><p className="copyright shell">© 2026 · Proposta visual por Ameer Mustafa</p></footer>
    <div className="mobileBar"><a href="#cardapio">Cardápio</a><a href={maps} target="_blank" rel="noreferrer">Como chegar <span>⌖</span></a></div>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  </>;
}
