const maps="https://www.google.com/maps/search/?api=1&query=Majestoso%2C+Largo+do+Paissandu+17%2C+Sao+Paulo&query_place_id=ChIJYxuIBlFYzpQRNPFaqNn8o1Q";
const categories=["Lanches","Beirutes","Café","Drinks","Sucos","Vitaminas","Salgados"];
export default function Home(){
 const schema={"@context":"https://schema.org","@type":"Restaurant",name:"Majestoso",description:"Demonstração conceitual não oficial do Majestoso.",address:{"@type":"PostalAddress",addressLocality:"São Paulo",addressRegion:"SP",postalCode:"01034-010",addressCountry:"BR",streetAddress:"Largo do Paissandú, 17 - República"}};
 return <>
 <header className="nav"><a className="wordmark" href="#inicio">MAJESTOSO<span>●</span></a><nav><a href="#sobre">O Majestoso</a><a href="#cardapio">Cardápio</a><a href="#ambiente">Ambiente</a><a href="#localizacao">Localização</a></nav><a className="navBtn" href={maps} target="_blank" rel="noreferrer">Como chegar ↗</a></header>
 <main id="inicio">
  <section className="hero"><div className="heroImg"/><div className="shade"/><div className="gridLine"/><div className="heroCopy"><p className="micro">LARGO DO PAISSANDÚ · CENTRO DE SÃO PAULO</p><h1>MAJES<span>TOSO</span></h1><p className="tag">Sabor no coração de São Paulo.</p><p className="sub">Lanches, café, bebidas e a energia de uma pausa no centro — em uma identidade que só o Majestoso tem.</p><div className="actions"><a className="btn red" href="#cardapio">Ver cardápio ↓</a><a className="btn dark" href={maps} target="_blank" rel="noreferrer">Como chegar ↗</a></div></div><div className="badge"><img src="/images/majestoso-neon.jpg" alt="Identidade visual neon do Majestoso"/></div></section>
  <section className="marquee" aria-label="Categorias"><div>LANCHES <i/> CAFÉ <i/> DRINKS <i/> SUCOS <i/> VITAMINAS <i/> SALGADOS</div></section>
  <section className="about" id="sobre"><div><p className="num">01</p><p className="micro redText">O MAJESTOSO</p></div><h2>Uma pausa com personalidade.</h2><div className="bodyCopy"><p>No ritmo do Centro, o Majestoso reúne balcão, mesas, café, lanches e bebidas em um ambiente vivo, direto e autenticamente paulistano.</p><p className="caption">Uma proposta digital inspirada nas cores, no neon e nos detalhes reais do espaço.</p></div></section>
  <section className="identity"><div className="neon"><img src="/images/majestoso-neon.jpg" alt="Personagem hambúrguer rei em neon, marca do Majestoso"/></div><div className="identityCopy"><p className="micro">IDENTIDADE</p><h2>O rei da<br/><em>pausa.</em></h2><p>Uma marca divertida, sem perder a presença. Vermelho, amarelo e neon transformados em uma linguagem visual forte e contemporânea.</p><div className="colors"><i className="c1"/><i className="c2"/><i className="c3"/><i className="c4"/></div></div></section>
  <section className="menu" id="cardapio"><div className="menuHead"><div><p className="num">02</p><p className="micro redText">CARDÁPIO</p></div><h2>Tem sempre<br/>uma boa escolha.</h2><p>As categorias vistas no próprio Majestoso, organizadas para receber itens, fotos e preços oficiais futuramente.</p></div><div className="categories">{categories.map((c,i)=><article key={c}><span>0{i+1}</span><h3>{c}</h3><b>→</b></article>)}</div><p className="menuNote">Nenhum preço ou produto específico foi inventado nesta demonstração.</p></section>
  <section className="pause"><div className="pauseCopy"><p className="micro">CENTRO DE SÃO PAULO</p><h2>Entre um compromisso e outro, uma pausa Majestosa.</h2><p>No Largo do Paissandú, o endereço acompanha o movimento do Centro Histórico e convida a entrar, sentar e recarregar.</p><a href={maps} target="_blank" rel="noreferrer">ABRIR NO GOOGLE MAPS ↗</a></div><div className="pauseImg"><img src="/images/majestoso-balcao.jpg" alt="Balcão do Majestoso com bebidas, frutas e salgados"/></div></section>
  <section className="gallery" id="ambiente"><div className="galleryHead"><p className="num">03</p><p className="micro">O AMBIENTE</p><h2>Vivo, iluminado<br/>e acolhedor.</h2></div><div className="photoWide"><img src="/images/majestoso-sala.jpg" alt="Interior do Majestoso com mesas, balcão e decoração"/><span>O salão e o balcão</span></div><div className="photoPair"><figure><img src="/images/majestoso-balcao.jpg" alt="Detalhes do balcão do Majestoso"/><figcaption>Detalhes que fazem parte da rotina</figcaption></figure><figure><img src="/images/majestoso-neon.jpg" alt="Neon Majestoso"/><figcaption>Uma identidade que acende o espaço</figcaption></figure></div></section>
  <section className="location" id="localizacao"><div><p className="num">04</p><p className="micro redText">LOCALIZAÇÃO</p><h2>No centro de tudo.</h2><address>Largo do Paissandú, 17<br/>República, São Paulo – SP<br/>CEP 01034-010, Brasil</address><p className="caption">No coração do Centro de São Paulo, com acesso direto pelo Largo do Paissandú.</p><a className="btn red" href={maps} target="_blank" rel="noreferrer">Como chegar ↗</a></div><iframe title="Localização do Majestoso" loading="lazy" src="https://www.google.com/maps?q=Majestoso%2C%20Largo%20do%20Paissandu%2017%2C%20Sao%20Paulo&output=embed"/></section>
  <section className="contact"><p className="micro">CONTATO & PEDIDOS</p><h2>Pronto para<br/>a próxima etapa.</h2><p>A estrutura está preparada para receber WhatsApp, telefone, Instagram, horários e pedidos assim que os dados oficiais forem confirmados.</p><div className="contactGrid"><span>WhatsApp<small>A adicionar</small></span><span>Instagram<small>A adicionar</small></span><span>Horários<small>A confirmar</small></span><span>Pedidos<small>A configurar</small></span></div></section>
 </main>
 <footer><a className="wordmark" href="#inicio">MAJESTOSO<span>●</span></a><address className="footerAddress"><a href={maps} target="_blank" rel="noreferrer">Largo do Paissandú, 17 — República<br/>São Paulo – SP, 01034-010, Brasil ↗</a></address><div className="notice"><b>DEMONSTRAÇÃO CONCEITUAL NÃO OFICIAL</b><p>Este site não é o site oficial do Majestoso. É uma demonstração conceitual criada exclusivamente para apresentação e avaliação. Desenvolvido por Ameer Mustafa.</p></div><p className="copy">© 2026 · Proposta visual por Ameer Mustafa</p></footer>
 <div className="mobileBar"><a href="#cardapio">Cardápio</a><a href={maps} target="_blank" rel="noreferrer">Como chegar ↗</a></div>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 </>;
}
