const maps = "https://www.google.com/maps/search/?api=1&query=Majestoso%2C+Largo+do+Paissandu+17%2C+Sao+Paulo&query_place_id=ChIJYxuIBlFYzpQRNPFaqNn8o1Q";

const categories = [
  {name:"Lanches",description:"Uma pausa cheia de sabor.",image:"lanches.webp"},
  {name:"Beirutes",description:"Generosos e bem servidos.",image:"beirutes.webp"},
  {name:"Café",description:"Aconchego em cada xícara.",image:"cafe.webp"},
  {name:"Drinks",description:"Gelados para bons momentos.",image:"drinks.webp"},
  {name:"Sucos",description:"Frescor para o seu dia.",image:"sucos.webp"},
  {name:"Vitaminas",description:"Cremosas e refrescantes.",image:"vitaminas.webp"},
  {name:"Salgados",description:"Dourados e irresistíveis.",image:"salgados.webp"},
];

function InstagramIcon() {
  return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4.1"/><circle className="fill" cx="17.4" cy="6.7" r="1"/></svg>;
}

function WhatsAppIcon() {
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.7a8.4 8.4 0 0 1-12.4 7.4L3 20.5l1.4-4.9a8.4 8.4 0 1 1 16.1-3.9Z"/><path d="M8.2 7.8c.2-.5.5-.5.8-.5h.5c.2 0 .4.1.5.4l.8 1.9c.1.3 0 .5-.2.7l-.6.7c-.2.2-.2.4-.1.7.5 1 1.3 1.8 2.3 2.3.3.2.5.1.7-.1l.8-1c.2-.2.4-.3.7-.2l1.8.8c.3.1.5.3.5.5 0 .3-.1 1.4-.7 2-.6.7-1.5.9-2.4.7-1.2-.2-2.8-.8-4.6-2.4-2.1-1.9-3.3-4.3-3.4-5.5 0-.5.1-.8.6-1Z"/></svg>;
}

export default function Home() {
  const schema = {"@context":"https://schema.org","@type":"Restaurant",name:"Majestoso",description:"Demonstração conceitual não oficial do Majestoso.",address:{"@type":"PostalAddress",streetAddress:"Largo do Paissandú, 17 - República",addressLocality:"São Paulo",addressRegion:"SP",postalCode:"01034-010",addressCountry:"BR"}};
  return <>
    <header className="nav" aria-label="Navegação principal"><a className="brand" href="#inicio" aria-label="Majestoso — início"><span>M</span><b>MAJESTOSO</b></a><nav><a href="#sobre">O Majestoso</a><a href="#cardapio">Cardápio</a><a href="#ambiente">Ambiente</a><a href="#localizacao">Localização</a></nav><a className="navCta" href="#cardapio">Ver cardápio <span>↘</span></a></header>
    <main id="inicio">
      <section className="hero shell"><div className="heroCopy"><p className="eyebrow">A LANCHONETE MAJESTOSO · CENTRO</p><h1>Sabor no<br/>coração de<br/><em>São Paulo.</em></h1><p className="lead">Lanches, café, bebidas e a energia de uma pausa no coração da cidade.</p><div className="actions"><a className="button primary" href="#cardapio">Ver cardápio <span>↘</span></a><a className="button outline" href={maps} target="_blank" rel="noreferrer">Como chegar <span>⌖</span></a></div><div className="heroMeta"><span>REPÚBLICA</span><span>01034-010</span></div></div><figure className="heroVisual"><img src="/images/majestoso-neon.jpg" alt="Identidade neon do Majestoso com o personagem coroado" fetchPriority="high"/><figcaption><span>Identidade Majestoso</span><b>NEON · VERMELHO · OURO</b></figcaption></figure></section>
      <section className="highlights shell" aria-label="Destaques do Majestoso"><article><span>01</span><div><b>Lanches</b><small>Para uma pausa completa</small></div></article><article><span>02</span><div><b>Café</b><small>Um clássico do dia a dia</small></div></article><article><span>03</span><div><b>Drinks</b><small>Opções para diferentes momentos</small></div></article><article><span>04</span><div><b>No coração de São Paulo</b><small>Largo do Paissandú</small></div></article></section>
      <section className="story shell" id="sobre"><div className="sectionIntro"><p className="eyebrow">01 · O MAJESTOSO</p><h2>Muito mais que<br/>uma <em>lanchonete.</em></h2></div><div className="storyGrid"><figure className="storyPhoto"><img src="/images/majestoso-sala.jpg" alt="Salão do Majestoso com mesas, balcão e iluminação" loading="lazy"/><figcaption>O salão e o balcão em uma só cena.</figcaption></figure><div className="storyCopy"><p>No ritmo do Centro, o Majestoso reúne balcão, mesas, café, lanches e bebidas em um ambiente vivo e autenticamente paulistano.</p><p>A proposta visual nasce do que já existe no espaço: madeira, luz quente, cores fortes e a presença marcante do neon.</p><ul><li><span>✦</span> Uma pausa no Centro de São Paulo</li><li><span>✦</span> Ambiente direto e acolhedor</li><li><span>✦</span> Identidade que não passa despercebida</li></ul></div></div></section>
      <section className="menu" id="cardapio"><div className="shell"><div className="menuHead"><div><p className="eyebrow">02 · CARDÁPIO</p><h2>Escolha o seu<br/><em>favorito.</em></h2></div><p>Explore as categorias do Majestoso. As imagens são representações visuais; itens e preços oficiais podem ser adicionados posteriormente.</p></div><div className="categoryGrid">{categories.map((category,index)=><article key={category.name} className="foodCard"><figure><img src={`/images/menu/${category.image}`} alt={`Imagem ilustrativa da categoria ${category.name}`} loading="lazy" width="800" height="600"/><span>{String(index+1).padStart(2,"0")}</span></figure><div><h3>{category.name}</h3><p>{category.description}</p></div></article>)}</div><p className="menuNote">Imagens ilustrativas das categorias. Não representam itens específicos do cardápio oficial.</p></div></section>
      <section className="ambience shell" id="ambiente"><div className="ambienceCopy"><p className="eyebrow">03 · O AMBIENTE</p><h2>Uma pausa com<br/><em>personalidade.</em></h2><p>Entre frutas frescas, bebidas, café e salgados, o balcão traduz o movimento cotidiano do Majestoso.</p><div className="detail"><span>LUZ QUENTE</span><span>MADEIRA</span><span>NEON</span></div></div><figure className="ambiencePhoto"><img src="/images/majestoso-balcao.jpg" alt="Balcão do Majestoso com bebidas, frutas e salgados" loading="lazy"/><figcaption><b>O balcão</b><span>Detalhes reais do espaço</span></figcaption></figure></section>
      <section className="location" id="localizacao"><div className="locationCard"><p className="eyebrow">04 · LOCALIZAÇÃO</p><h2>No centro<br/>de tudo.</h2><address>Largo do Paissandú, 17<br/>República, São Paulo – SP<br/>01034-010, Brasil</address><a className="button mapButton" href={maps} target="_blank" rel="noreferrer">Como chegar <span>⌖</span></a><div className="contactBlock" aria-label="Canais de contato"><p>CONTATO</p><div><span className="socialButton" aria-disabled="true" title="Link oficial a confirmar"><InstagramIcon/><b>Instagram</b><small>Link a confirmar</small></span><span className="socialButton" aria-disabled="true" title="Link oficial a confirmar"><WhatsAppIcon/><b>WhatsApp</b><small>Link a confirmar</small></span></div></div></div><div className="mapEmbed"><iframe title="Mapa do Majestoso no Largo do Paissandú" src="https://www.google.com/maps?q=Majestoso%2C%20Largo%20do%20Paissandu%2017%2C%20Sao%20Paulo&output=embed" loading="eager" referrerPolicy="no-referrer-when-downgrade" allowFullScreen></iframe><a href={maps} target="_blank" rel="noreferrer">Abrir no Google Maps ↗</a></div></section>
    </main>
    <footer><div className="footerTop shell"><a className="brand footerBrand" href="#inicio"><span>M</span><b>MAJESTOSO</b></a><div><p className="footerLabel">NAVEGAÇÃO</p><a href="#sobre">O Majestoso</a><a href="#cardapio">Cardápio</a><a href="#ambiente">Ambiente</a></div><address><p className="footerLabel">ENDEREÇO</p><a href={maps} target="_blank" rel="noreferrer">Largo do Paissandú, 17<br/>República, São Paulo – SP<br/>01034-010, Brasil ↗</a></address><div className="footerSocial"><p className="footerLabel">CONTATO</p><div><span aria-disabled="true" title="Instagram oficial a confirmar"><InstagramIcon/><span>Instagram</span></span><span aria-disabled="true" title="WhatsApp oficial a confirmar"><WhatsAppIcon/><span>WhatsApp</span></span></div><small>Links oficiais a confirmar</small></div></div><div className="disclaimer shell"><b>DEMONSTRAÇÃO CONCEITUAL NÃO OFICIAL</b><p>Este site não é o site oficial do Majestoso. É uma demonstração conceitual criada exclusivamente para apresentação e avaliação. Desenvolvido por Ameer Mustafa.</p></div><p className="copyright shell">© 2026 · Proposta visual por Ameer Mustafa</p></footer>
    <div className="mobileBar"><a href="#cardapio">Cardápio</a><a href={maps} target="_blank" rel="noreferrer">Como chegar <span>⌖</span></a></div>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  </>;
}
